apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: giga-ai-agent-database
  namespace: {{ namespace }}
  labels:
    app.kubernetes.io/name: giga-ai-agent-database
    app.kubernetes.io/part-of: giga-ai-agent
    app.kubernetes.io/component: core
spec:
  host: {{ db_host }}
  trafficPolicy:
    portLevelSettings:
      - port:
          number {{ db_port }}
        tls:
          mode: DISABLE
  workloadSelector:
    istio: {{ namespace }}-egressgateway
  exportTo:
    - "."