apiVersion: v1
kind: Service
metadata:
  name: giga-ai-agent-database
  namespace: {{ namespace }}
  labels:
    app.kubernetes.io/name: giga-ai-agent-database
    app.kubernetes.io/part-of: giga-ai-agent
    app.kubernetes.io/component: core
spec:
  ports:
    - name: tcp
      protocol: TCP
      port: {{ db_port }}
      targetPort: {{ db_port }}