apiVersion: v1
kind: Service
metadata:
  name: giga-ai-agent-kafka-{{ kafka_id }}
  namespace: {{ namespace }}
  labels:
    app.kubernetes.io/name: giga-ai-agent-kafka-{{ kafka_id }}
    app.kubernetes.io/part-of: giga-ai-agent
    app.kubernetes.io/component: core
spec:
  ports:
    - name: tcp
      protocol: TCP
      port: {{ kafka_port }}
      targetPort: {{ kafka_port }}