apiVersion: v1
kind: Service
metadata:
  name: {{ name }}
  namespace: {{ namespace }}
  labels:
    app.kubernetes.io/name: giga-ai-agent-{{ name }}-service
    app.kubernetes.io/part-of: giga-ai-agent
    app.kubernetes.io/component: core
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: {{ ext_https_port }}
      targetPort: {{ ext_https_port }}