apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ name }}-rule
  namespace: {{ namespace }}
  labels:
    app.kubernetes.io/name: giga-ai-agent-{{ name }}-virtual-service
    app.kubernetes.io/part-of: giga-ai-agent
    app.kubernetes.io/component: core
spec:
  exportTo:
    - "."
  hosts:
    - {{ host }}
  gateways:
    - mesh
    - {{ namespace }}/giga-ai-agent-egress-gateway
  http:
      - match:
        - gateways:
            - mesh
          port: 80
        route:
          - destination:
              host: giga-ai-agent-egressgw.{{ namespace }}.svc.cluster.local
              subset: {{ name }}
              port:
                number: 80
      - match:
          - gateways:
              - {{ namespace }}/giga-ai-agent-egress-gateway
            port: 80
        route:
          - destination:
              host: {{ host }}
              port:
                number: {{ ext_https_port }}