apiVersion: batch/v1
kind: Job
metadata:
  name: core-db-migrate
  namespace: {{ namespace }}
  labels:
    app.kubernetes.io/name: db-migrate-job
    app.kubernetes.io/component: core
    app.kubernetes.io/part-of: giga-ai-agent
spec:
  template:
    metadata:
      labels:
        app: db-migrate
        app.kubernetes.io/component: core
        app.kubernetes.io/part-of: giga-ai-agent
        app.network.policy: restricted
        sidecar.istio.io/proxyCPU: {{ db_migrate.istio.requests.cpu }}
        sidecar.istio.io/proxyCPULimit: {{ db_migrate.istio.limits.cpu }}
        sidecar.istio.io/proxyMemory: {{ db_migrate.istio.requests.memory }}
        sidecar.istio.io/proxyMemoryLimit: {{ db_migrate.istio.limits.memory }}
    spec:
      restartPolicy: Never
      volumes:
        - name: vault-agent-config
          configMap:
            name: db-migrate-vault-agent
            items:
              - key: vault-agent-config.hcl
                path: vault-agent-config.hcl
        - name: liquibase-props
          emptyDir:
            sizeLimit: 1Mi
        - name: vault-token
          emptyDir:
            sizeLimit: 1Mi
        - name: vault-role
          secret:
            secretName: vault-role

      containers:
        - name: db-migrate
          image: snapshots.docker-registry.ra-tech.pro/{{ image_tag }}
          securityContext:
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - mountPath: /config/liquibase
              name: liquibase-props
              readOnly: true
          resources:
            requests:
              cpu: {{ db_migrate.requests.cpu }}
              memory: {{ db_migrate.requests.memory }}
            limits:
              cpu: {{ db_migrate.limits.cpu }}
              memory: {{ db_migrate.limits.memory }}
        - name: vault-agent
          image: hashicorp/vault:1.18
          args:
            - agent
            - -config=/vault/agent/vault-agent-config.hcl
            - -log-level=info
          env:
            - name: VAULT_ADDR
              value: {{ vault.url }}
          volumeMounts:
            - mountPath: /vault/agent
              name: vault-agent-config
            - mountPath: /vault/secrets/liquibase
              name: liquibase-props
            - mountPath: /vault/token
              name: vault-token
            - mountPath: /vault/role
              name: vault-role
              readOnly: true
          resources:
            requests:
              cpu: {{ db_migrate.vault.requests.cpu }}
              memory: {{ db_migrate.vault.requests.memory }}
            limits:
              cpu: {{ db_migrate.vault.limits.cpu }}
              memory: {{ db_migrate.vault.limits.memory }}

      imagePullSecrets:
        - name: docker-registry-creds