apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: giga-ai-agent-core-destination
  namespace: {{ namespace }}
  labels:
    app.kubernetes.io/part-of: giga-ai-agent
    app.kubernetes.io/component: core
spec:
  host: giga-ai-agent-core-service.{{ namespace }}.svc.cluster.local
  exportTo:
    - "."
  workloadSelector:
    matchLabels:
      app: giga-ai-agent-core