apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: giga-ai-agent-egress-gateway
  namespace: {{ namespace }}
  labels:
    app.kubernetes.io/part-of: giga-ai-agent
    app.kubernetes.io/component: core
spec:
  selector:
    istio: {{ namespace }}-egressgateway
  servers:
    - port:
        number: 80
        name:  http
        protocol: HTTP
      hosts:
        - {{ solr_host }}
        - {{ vault_host }}
        - {{ giga_auth_host }}
        - {{ giga_chat_host }}
        - {{ telegram_api_host }}
        - {{ yandex_gpt_auth_host }}
        - {{ yandex_gpt_api_host }}
        - {{ hfs_host }}
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - {{ solr_host }}
        - {{ vault_host }}
        - {{ giga_chat_host }}
        - {{ telegram_api_host }}
        - {{ yandex_gpt_auth_host }}
        - {{ yandex_gpt_api_host }}
        - {{ hfs_host }}
      tls:
        mode: PASSTHROUGH
    - port:
        number: 9443
        name: https-9
        protocol: HTTPS
      hosts:
        - {{ giga_auth_host }}
      tls:
        mode: PASSTHROUGH
    - port:
        number: {{ egress_tcp_port }}
        name: tcp
        protocol: TCP
      hosts:
        - {{ db_host }}