apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: giga-ai-agent-egress-gateway
  namespace: {{ namespace }}
  labels:
    app.kubernetes.io/part-of: giga-ai-agent
    app.kubernetes.io/component: core
spec:
  selector:
    istio: {{ namespace }}-egressgateway
  servers:
    - port:
        number: 80
        name:  http
        protocol: HTTP
      hosts:
        - {{ solr.host }}
        - {{ vault.host }}
        - {{ giga.auth.host }}
        - {{ giga.chat.host }}
        - {{ telegram.api.host }}
        - {{ yandex.gpt.auth.host }}
        - {{ yandex.gpt.api.host }}
        - {{ hfs.host }}
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - {{ solr.host }}
        - {{ vault.host }}
        - {{ giga.chat.host }}
        - {{ telegram.api.host }}
        - {{ yandex.gpt.auth.host }}
        - {{ yandex.gpt.api.host }}
        - {{ hfs.host }}
    - port:
        number: 9443
        name: https-9
        protocol: HTTPS
      hosts:
        - {{ giga.auth.host }}
    - port:
        number: {{ egress_tcp_port }}
        name: tcp
        protocol: TCP
      hosts:
        - {{ db_host }}
    {% for server in kafka.bootstrap_servers %}
    - port:
        number: {{ server.port }}
        name: kafka-port-{{ server.port }}
        protocol: TCP
      hosts:
        - {{ server.host }}
    {% endfor %}
