apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: egw-destination
  namespace: {{ namespace }}
  labels:
    app.kubernetes.io/part-of: giga-ai-agent
    app.kubernetes.io/component: core
spec:
  host: giga-ai-agent-egressgw.{{ namespace }}.svc.cluster.local
  subsets:
    - name: solr
    - name: vault
  exportTo:
    - "."