apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-network-policy
  namespace: {{ namespace }}
  labels:
    app.kubernetes.io/part-of: giga-ai-agent
    app.kubernetes.io/component: istio
spec:
  podSelector:
    matchLabels:
      app.network.policy: egress
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ namespace }}
  egress:
    - {}