apiVersion: v1
kind: Service
metadata:
  name: giga-ai-agent-core-service
  namespace: {{ namespace }}
  labels:
    app.kubernetes.io/name: giga-ai-agent-core-service
    app.kubernetes.io/part-of: giga-ai-agent
    app.kubernetes.io/component: core
spec:
  selector:
    app: giga-ai-agent-core
  ports:
    - name: http-rest-api
      protocol: TCP
      port: 8080
      targetPort: core-rest-api
    - name: http-actuator
      protocol: TCP
      port: 8081
      targetPort: core-actuator