apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: giga-ai-agent-core-rule
  namespace: {{ namespace }}
  labels:
    app.kubernetes.io/part-of: giga-ai-agent
    app.kubernetes.io/component: core
spec:
  exportTo:
    - "."
    - istio-system
  hosts:
    - {{ host }}
  gateways:
    - "{{ namespace }}/giga-ai-agent-ingress-gateway"
    - mesh
  http:
    - name: core-actuator-route
      match:
        - uri:
            prefix: "/actuator"
      route:
        - destination:
            host: giga-ai-agent-core-service.{{ namespace }}.svc.cluster.local
            port:
              number: 8081
    - name: core-api-route
      match:
        - uri:
            prefix: "/"
      route:
        - destination:
            host: giga-ai-agent-core-service.{{ namespace }}.svc.cluster.local
            port:
              number: 8080