management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus
          - health
          - info
          - metrics
  endpoint:
    health:
      access: unrestricted
      show-details: always
      probes:
        enabled: true
      group:
        liveness:
          include:
            - livenessState
        readiness:
          include:
            - readinessState
    prometheus:
      access: unrestricted
      metrics:
        export:
          enabled: true
  server:
    port: 8081
  metrics:
    distribution:
      percentiles-histogram[http.server.requests]: true
      percentiles[http.server.request]: 0.90, 0.95, 0.99
      slo[http.server.requests]: 50ms, 100ms, 250ms, 500ms, 1s, 2s, 3s
    enable:
      jvm: true

spring:
  application:
    name: GIGA AI Agent
    version: @revision@
  mvc:
    problemdetails:
      enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 110MB
      file-size-threshold: 110MB
  liquibase:
    change-log: db/changelog-root.yaml

server:
  servlet:
    encoding:
      force: true
app:
  monitoring:
    app-name: @name@
    app-version: @revision@
    pod-name: ${POD_NAME:core-local-test}
    pod-namespace: ${POD_NAMESPACE:core-local-test}
    node-name: ${NODE_NAME:core-local-test}
