logging:
  level:
    root: ${ROOT_LOGGING_LEVEL:DEBUG}

spring:
  liquibase:
    enabled: ${LIQUIBASE_ENABLED:false}
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

app:
  giga-chat:
    auth-api-base-url: ${GIGA_CHAT_AUTH_API_BASE_URL}
    api-base-url: ${GIGA_CHAT_API_BASE_URL}
    request-timeout-ms: ${GIGA_CHAT_API_REQUEST_TIMEOUT_MS}
    max-retries: ${GIGA_CHAT_API_MAX_RETRIES}
    retry-timeout-ms: ${GIGA_CHAT_API_RETRY_TIMEOUT_MS}
    client-id: ${GIGA_CHAT_CLIENT_ID}
    auth-key: ${GIGA_CHAT_AUTH_KEY}
    auth-retry-timeout-ms: ${GIGA_CHAT_AUTH_RETRY_TIMEOUT_MS}
    embeddings-inputs-max-count: ${GIGA_CHAT_EMBEDDINGS_INPUTS_MAX_COUNT}
    stub-embeddings: ${GIGA_CHAT_STUB_EMBEDDINGS}
  telegram:
    api:
      rest-api-base-url: ${TELEGRAM_BOT_REST_BASE_URL}
      api-token: ${TELEGRAM_BOT_TOKEN}
      update-limit: ${TELEGRAM_BOT_API_UPDATE_LIMIT}
      update-timeout-sec: ${TELEGRAM_BOT_UPDATE_TIMEOUT_SEC}
      request-timeout-ms: ${TELEGRAM_BOT_API_REQUEST_TIMEOUT_MS}
      max-retries: ${TELEGRAM_BOT_API_REQUEST_MAX_RETRIES}
    bot:
      enabled: true
      updates-queue-capacity: ${TELEGRAM_BOT_UPDATES_QUEUE_CAPACITY}
      ai-model-type: ${TELEGRAM_BOT_AI_MODEL_TYPE}
      updates-handlers-count: ${TELEGRAM_BOT_UPDATE_HANDLERS_COUNT}
  llm-text-processor:
    base-url: ${LLM_TEXT_PROCESSOR_BASE_URL}
    request-timeout-ms: ${LLM_TEXT_PROCESSOR_REQUEST_TIMEOUT_MS}
    max-retries: ${LLM_TEXT_PROCESSOR_MAX_RETRIES}
  ya-gpt:
    enabled: ${YA_GPT_ENABLED:false}
    auth-api-base-url: ${YA_GPT_AUTH_API_BASE_URL}
    api-base-url: ${YA_GPT_API_BASE_URL}
    o-auth-token: ${YA_GPT_O_AUTH_TOKEN}
    request-timeout-ms: ${YA_GPT_REQUEST_TIMEOUT_MS}
    max-retries: ${YA_GPT_MAX_RETIRES}
    retry-timeout-ms: ${YA_GPT_RETRY_TIMEOUT_MS}
    cloud-catalog-id: ${YA_GPT_CLOUD_CATALOG_ID}
  hfs:
    api-base-url: ${HFS_API_BASE_URL}
    request-timeout-ms: ${HFS_API_REQUEST_TIMEOUT_MS}
    max-retries: ${HFS_API_MAX_RETRIES}
    retry-timeout-ms: ${HFS_API_RETRY_TIMEOUT_MS}
    base-folder: ${HFS_BASE_FOLDER}
    user: ${HFS_USER}
    password: ${HFS_PASSWORD}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    document-processing-topic: ${KAFKA_DOCUMENT_PROCESSING_TOPIC}