apiVersion: v1
kind: ServiceAccount
metadata:
  name: giga-ai-agent-egressgw-service-account
  namespace: {{ namespace }}
  labels:
    app: giga-ai-agent-egressgw
    app.kubernetes.io/name: giga-ai-agent-egressgw
    app.kubernetes.io/component: istio-egressgw
    app.kubernetes.io/part-of: giga-ai-agent
    istio.io/rev: 1-18-2