apiVersion: v1
kind: Service
metadata:
  name: giga-ai-agent-egressgw
  namespace: {{ namespace }}
  labels:
    app: giga-ai-agent-egressgw
    app.kubernetes.io/name: giga-ai-agent-egressgw
    app.kubernetes.io/component: istio-egressgw
    app.kubernetes.io/part-of: giga-ai-agent
    istio.io/rev: 1-18-2
spec:
  ports:
    - name: tcp-postgres
      port: {{ egress_tcp_port }}
      protocol: TCP
      targetPort: {{ egress_tcp_port }}
    {% for server in kafka.bootstrap_servers %}
    - name: tcp-kafka-{{ server.port }}
      protocol: TCP
      targetPort: {{ server.egress_port }}
    {% endfor %}
    - name: http
      port: 80
      protocol: TCP
      targetPort: 18080
    - name: https
      port: 443
      protocol: TCP
      targetPort: 10443
  selector:
    app: giga-ai-agent-egressgw
    istio: {{ namespace }}-egressgateway
  type: ClusterIP