apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: giga-ai-agent-egressgw-sds
  namespace: {{ namespace }}
  labels:
    app: giga-ai-agent-egressgw
    app.kubernetes.io/name: giga-ai-agent-egressgw
    app.kubernetes.io/component: istio-egressgw
    app.kubernetes.io/part-of: giga-ai-agent
    istio.io/rev: 1-18-2
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch", "list"]
